name = "ImGuiOpenGL2Backend"
uuid = "c105bd9b-9289-4129-acf4-4c081b46d160"
authors = ["purism "]
version = "0.1.0"

[deps]
LibCImGui = "9be01004-c4f5-478b-abeb-cb32b114cf5e"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
